### ISSUE TITLE
.grid.justify-center overrides descendant text-aligns

### ISSUE THREAD

**Issue by snsxn** [leejordan/reflex#57]
Hi, I'm really happy with this grid and I'm using it a lot, thank you!

I have an issue maybe because I'm totally dumb...

When using `justify-center`in `grid`, every element inside it can't have different text align options:

```html
<div class="container">
   <div class="grid justify-center">
      <div class="col-6">
         <p style="text-align:center>Hi</p>
      </div>
   </div>
</div>
```

I'm missing something?

P.D: I'm currently commenting these part of the code to work again with text-aligns:
```css
.justify-center.grid [class^="col-"] {
  text-align: left;
  text-align: start;
  /*-moz-text-align-last: left;
  -moz-text-align-last: start;
  text-align-last: left;
  text-align-last: start;*/
}
```
